<?php

namespace Push\EntityBundle\Repository;

/**
 * WebNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
